name: Build FlameCord
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  version: 1.19
  branch: dev/1.19
  debug: 'false'

jobs:
  release:
    strategy:
      matrix:
        jdk: [17.0.3]
        java: ['temurin']
        os: [ubuntu-20.04]

    if: "!startsWith(github.event.commits[0].message, '[CI-Skip]')"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout action
        uses: actions/checkout@main

      - name: Set up JDK ${{ matrix.java }} ${{ matrix.jdk }}
        uses: actions/setup-java@main
        with:
          distribution: ${{ matrix.java }}
          java-version: ${{ matrix.jdk }}

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
          echo "workflow=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      
      - name: Update submodule
        run: |
          rm -rf Waterfall && git clone --recursive https://github.com/PaperMC/Waterfall
          cd Waterfall && rm -rf BungeeCord && git clone --recursive https://github.com/SpigotMC/BungeeCord
          cd BungeeCord/native && rm -rf mbedtls && git clone --recursive https://github.com/Mbed-TLS/mbedtls.git
          # rm -rf zlib && git clone --recursive https://github.com/cloudflare/zlib.git

      - name: Build
        run: ./flamecord b
        
      - name: Release Artifacts
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build-${{ env.workflow }}"
          automatic_release_tag: build-${{ env.workflow }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: FlameCord-Proxy/bootstrap/target/FlameCord.jar
          prerelease: false
