name: Build FlameCord
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  version: 1.19
  branch: dev/1.19
  debug: 'false'

jobs:
  release:
    strategy:
      matrix:
        jdk: [17.0.3]
        java: ['temurin']
        os: [ubuntu-20.04]

    if: "!startsWith(github.event.commits[0].message, '[CI-Skip]')"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout action
        uses: actions/checkout@main

      - name: Set up JDK ${{ matrix.java }} ${{ matrix.jdk }}
        uses: actions/setup-java@main
        with:
          distribution: ${{ matrix.java }}
          java-version: ${{ matrix.jdk }}
          cache: 'maven'

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"

      - name: Build
        run: ./flamecord b
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: Artifacts
          path: FlameCord-Proxy/bootstrap/target
